### ISSUE TITLE
Not able to run with listed steps in instruction

### ISSUE THREAD

**Issue by jpatel3** [nteract/nteract.io#24]
Running into following error post `npm install`, and while trying run - `npm run start`

```
/code/nteract.io/next.config.js:5
    webpack: (config, { dev }) => {
                      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at loadConfig 
```

**Comment by rgbkrk** [comment]
Hey thanks for reporting this. I'll go ahead and start a fresh install myself to see if I can fix this. Our current README says to run `npm run dev` after the install too

Actually, come to think of it... What version of node are you on? Most files are transpiled, this one is likely not since it's read before next.js is booted up.

**Comment by jpatel3** [comment]
Tried - `npm run dev`, it throws same error. 

node version -  `v5.0.0`

**Comment by rgbkrk** [comment]
Ah yeah I'm on node v8.0.0. I certainly recommend `v6`+.

However, I've hopefully addressed it in #25 -- want to check that out? If you want to try locally, you can delete just the `{ dev }` part out of `next.config.js` on your copy.

**Comment by jpatel3** [comment]
Sure, will try after the update.

```
After removing { dev }, it still runs into issue -
 ERROR  Failed to compile with 1 errors                                                                                   5:58:08 PM

 error  in ./pages/_error.js?entry

Syntax Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at Array.map (native)

 @ multi ./pages/_error.js?entry

Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
> Ready on http://localhost:3000
{ [Error: Cannot find module /Users/Code/nteract.io/.next/dist/pages/_error] code: 'ENOENT' }
{ [Error: Cannot find module /Users/Code/nteract.io/.next/dist/pages/_error] code: 'ENOENT' }
```

**Comment by rgbkrk** [comment]
Did you upgrade to node v6.x as well?

**Comment by jpatel3** [comment]
Updated version, and now on node 6.11.3, also tried with 8.5.0

Looks like it's not able to compile sass. Here is the log. Do I need to run any other step in between?

```
> Reloading webpack due to inconsistant state of pages(s): /, /, /, /, /, /
> Using external babel configuration
> Location: "/Users/Code/nteract.io/.babelrc"
> Using "webpack" config function defined in next.config.js.
{ Error: Cannot find module './header.scss'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Code/nteract.io/components/header/header.js:1:1)
    at Module._compile (module.js:570:32)
    at Module._compile (/Users/Code/nteract.io/node_modules/source-map-support/source-map-support.js:483:25)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' }

 ERROR  Failed to compile with 6 errors                                                                                   4:57:35 AM

 error  in ./components/layout/layout.scss

Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/Code/nteract.io/node_modules/node-sass/vendor'
....

 error  in ./components/content-section/content-section.scss

Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/Code/nteract.io/node_modules/node-sass/vendor'
.....
```

**Comment by rgbkrk** [comment]
I think if the install failed an earlier time you'll have to run `rm -rf node_modules` and run the install over again.

I applaud your patience and diligence. 😄

**Comment by jpatel3** [comment]
Awesome. Works fine now. I'll see if those new contributor friendly tickets I can tackle in free time.

Appriciate you also being kind in responding 😊
