### ISSUE TITLE
Migrating to nteract's now account

### ISSUE THREAD

**Issue by rgbkrk** [nteract/nteract.io#34]
This is a tiny ops log / plan. I'll update it as I go along.

Steps:

1. Deploy nteract.io following guidance
2. Deploy slackin to nteract account
3. Attempt to switch domain
4. Set DNS for deployments in (1) and (2)

**Comment by rgbkrk** [comment]
nteract.io deployed to https://nteractio-fqzdqjnvmd.now.sh

manage google recaptcha here: https://www.google.com/recaptcha/admin

slack inviter deployed here: https://slackin-fiovbqqyjk.now.sh

**Comment by rgbkrk** [comment]
Steps to run after switching domain owner:

```
now alias https://nteractio-fqzdqjnvmd.now.sh https://nteract.io
now alias https://slackin-fiovbqqyjk.now.sh https://slack.nteract.io
```

**Comment by rgbkrk** [comment]
It appears that zeit is still having issues with domain deletion in automation: https://github.com/zeit/now-cli/issues/952

I'm going to delete our resources and see if it lets us remove the domain and bring it back.

**Comment by rgbkrk** [comment]
Intermittent erroring:

```
$ now alias https://nteractio-fqzdqjnvmd.now.sh https://nteract.io
> nteract.io is a custom domain.
> Verifying the DNS settings for nteract.io (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for nteract.io
> Error! Unknown error: Error: Invalid challenge response for nteract.io. Make sure the DNS records are correct.
Error: Invalid challenge response for nteract.io. Make sure the DNS records are correct.
    at module.exports.EventEmitter.createCert.domain.retry (/snapshot/now-cli/dist/now.js:906:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by rgbkrk** [comment]
Still getting this error, I'm assuming we have to wait on DNS. 😭 

```
$ now alias https://nteractio-fqzdqjnvmd.now.sh https://nteract.io
> nteract.io is a custom domain.
> Verifying the DNS settings for nteract.io (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for nteract.io
> Error! Unknown error: Error: Invalid challenge response for nteract.io. Make sure the DNS records are correct.
Error: Invalid challenge response for nteract.io. Make sure the DNS records are correct.
    at module.exports.EventEmitter.createCert.domain.retry (/snapshot/now-cli/dist/now.js:906:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by rgbkrk** [comment]
Hey! Here's some better messaging / insight:

```
$ now alias https://nteractio-fqzdqjnvmd.now.sh https://nteract.io
> nteract.io is a custom domain.
> Verifying the DNS settings for nteract.io (see https://zeit.world for help)
> Detected zeit.world nameservers! Configuring records.
> DNS Configured! Verifying propagation…
> Error! > We configured the DNS settings for your alias, but we were unable to verify that they've propagated. Please try the alias again later.
```

**Comment by rgbkrk** [comment]
`alias`ing is now working so I just aliased our two main services...

Annnnnd done! Ok, now everyone on the nteract team account can make deploys, alias, etc. 🎉
